In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Jamal1*@localhost:5432/retail_analytics_db"
)

query = "SELECT * FROM retail.stg_superstore"

df = pd.read_sql(query, engine)

print(df.shape)

(9994, 21)

In [2]:
## lets limit our wuery to 5
query = "SELECT * FROM retail.stg_superstore LIMIT 5"

df = pd.read_sql(query, engine)

print(df.shape)

df.head()

(5, 21)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

# Build dimension tables from staging.
Starting with:
dim_customers
This is the perfect first dimension because:
clear business entity
easy deduplication
introduces surrogate keys later
So the First Step is Load staging table

In [3]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Jamal1*@localhost:5432/retail_analytics_db"
)

query = "SELECT * FROM retail.stg_superstore"

df = pd.read_sql(query, engine)

print(df.shape)
df.head()

(9994, 21)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

# Then Create Customer Dimension in Python AND Add Surrogate Key

In [4]:
dim_customers = (
    df[
        [
            "customer_id",
            "customer_name",
            "segment"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print(dim_customers.shape)

dim_customers.head()

(793, 3)

  customer_id    customer_name    segment
0    CG-12520      Claire Gute   Consumer
1    DV-13045  Darrin Van Huff  Corporate
2    SO-20335   Sean O'Donnell   Consumer
3    BH-11710  Brosina Hoffman   Consumer
4    AA-10480     Andrew Allen   Consumer

# Add Surrogate Key

In [5]:
dim_customers.insert(
    0,
    "customer_key",
    range(1, len(dim_customers) + 1)
)

print(dim_customers.shape)

dim_customers.head()

(793, 4)

   customer_key customer_id    customer_name    segment
0             1    CG-12520      Claire Gute   Consumer
1             2    DV-13045  Darrin Van Huff  Corporate
2             3    SO-20335   Sean O'Donnell   Consumer
3             4    BH-11710  Brosina Hoffman   Consumer
4             5    AA-10480     Andrew Allen   Consumer

In [6]:
# Duplicate Check
dim_customers["customer_id"].duplicated().sum()

0

# Load into PostgreSQL

In [7]:
dim_customers.to_sql(
    "dim_customers",
    engine,
    schema="retail",
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

print("dim_customers loaded successfully")

dim_customers loaded successfully

# Verify Load

In [8]:
pd.read_sql(
    "SELECT COUNT(*) FROM retail.dim_customers",
    engine
)

   count
0    793

# Create Product Dimension dim_production

In [9]:
dim_products = (
    df[
        [
            "product_id",
            "product_name",
            "category",
            "sub_category"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print(dim_products.shape)

dim_products.head()

(1894, 4)

,product_id,product_name,category,sub_category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

# STEP 2 — Add Surrogate Key to dim_products

In [10]:
dim_products.insert(
    0,
    "product_key",
    range(1, len(dim_products) + 1)
)

dim_products.head()

,product_key,product_id,product_name,category,sub_category
0,1,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,2,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,3,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,4,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,5,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

# STEP 3 — Duplicate Check

In [11]:
dim_products["product_id"].duplicated().sum()

32

In [12]:
# Let’s Investigate 

dim_products[
    dim_products["product_id"].duplicated(keep=False)
].sort_values("product_id")

,product_key,product_id,product_name,category,sub_category
1364,1365,FUR-BO-10002213,"Sauder Forest Hills Library, Woodland Oak Finish",Furniture,Bookcases
1259,1260,FUR-BO-10002213,DMI Eclipse Executive Suite Bookcases,Furniture,Bookcases
64,65,FUR-CH-10001146,"Global Value Mid-Back Manager's Chair, Gray",Furniture,Chairs
124,125,FUR-CH-10001146,"Global Task Chair, Black",Furniture,Chairs
1011,1012,FUR-FU-10001473,DAX Wood Document Frame,Furniture,Furnishings
...,...,...,...,...,...
892,893,TEC-PH-10002200,Samsung Galaxy Note 2,Technology,Phones
1399,1400,TEC-PH-10002310,Plantronics Calisto P620-M USB Wireless Speake...,Technology,Phones
975,976,TEC-PH-10002310,Panasonic KX T7731-B Digital phone,Technology,Phones
728,729,TEC-PH-10004531,OtterBox Commuter Series Case - iPhone 5 & 5s,Technology,Phones
1435,1436,TEC-PH-10004531,AT&T CL2909,Technology,Phones

In [13]:
# Use Composite Grain
# product_id + product_name

dim_products.duplicated(
    subset=[
        "product_id",
        "product_name",
        "category",
        "sub_category"
    ]
).sum()

0

# STEP 4 — Load Into PostgreSQL

In [14]:

dim_products.to_sql(
    "dim_products",
    engine,
    schema="retail",
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

print("dim_products loaded successfully")

dim_products loaded successfully

# Create  Geography dim_geography

In [21]:
dim_geography = (
    df[
        [
            "country",
            "city",
            "state",
            "postal_code",
            "region"
    
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)
print(dim_geography.shape)
dim_geography.head()

(632, 5)

         country             city           state postal_code region
0  United States        Henderson        Kentucky       42420  South
1  United States      Los Angeles      California       90036   West
2  United States  Fort Lauderdale         Florida       33311  South
3  United States      Los Angeles      California       90032   West
4  United States          Concord  North Carolina       28027  South

# Add surrogate key

In [22]:
dim_geography.insert(
    0,
    "geography_key",
    range(1,len(dim_geography) + 1)
)
dim_geography.head()

,geography_key,country,city,state,postal_code,region
0,1,United States,Henderson,Kentucky,42420,South
1,2,United States,Los Angeles,California,90036,West
2,3,United States,Fort Lauderdale,Florida,33311,South
3,4,United States,Los Angeles,California,90032,West
4,5,United States,Concord,North Carolina,28027,South

In [24]:
dim_geography.tail(10)

,geography_key,country,city,state,postal_code,region
622,623,United States,Oswego,Illinois,60543,Central
623,624,United States,Coon Rapids,Minnesota,55433,Central
624,625,United States,San Clemente,California,92672,West
625,626,United States,Dublin,California,94568,West
626,627,United States,San Luis Obispo,California,93405,West
627,628,United States,Springdale,Arkansas,72762,South
628,629,United States,Lodi,California,95240,West
629,630,United States,La Porte,Texas,77571,Central
630,631,United States,Mason,Ohio,45040,East
631,632,United States,Woodstock,Georgia,30188,South

# Duplicate Check

In [25]:
# we use this grain for duplicate check
# country + state + city + postal_code + region >> subset
dim_geography.duplicated(
    subset= [
        "country",
        "city",
        "state",
        "postal_code",
        "region"
    ]
).sum()

0

In [ ]:
# Load into Postgre SQL

In [27]:
dim_geography.to_sql(
    "dim_geography",
    engine,
    schema="retail",
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)


print("dim_geography  loaded successfully")

dim_geography  loaded successfully

# Create  Shipping dim_shipping

In [28]:
dim_shipping = (
    df[
        [
            "ship_mode"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print(dim_shipping.shape)

dim_shipping.head()

(4, 1)

        ship_mode
0    Second Class
1  Standard Class
2     First Class
3        Same Day

In [ ]:
# Add Surrogate Key

In [29]:
dim_shipping.insert(
    0,
    "shipping_key",
    range(1,len(dim_shipping) + 1)
)
dim_shipping.head()

   shipping_key       ship_mode
0             1    Second Class
1             2  Standard Class
2             3     First Class
3             4        Same Day

# Duplicate Check

In [30]:
dim_shipping["ship_mode"].duplicated().sum()

0

# Load To PostgreSQL

In [31]:
dim_shipping.to_sql(
    "dim_shipping",
    engine,
    schema="retail",
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

print("dim_shipping loaded successfully")

dim_shipping loaded successfully

# Create Date Dimension dim_dates

In [32]:
# Step 1Convert dates first

df["order_date"] = pd.to_datetime(df["order_date"])
df["ship_date"] = pd.to_datetime(df["ship_date"])

In [33]:
# Step 2 Combine Unique Dates
all_dates = pd.concat(
    [
        df["order_date"],
        df["ship_date"]
    ]
).drop_duplicates().sort_values().reset_index(drop=True)

print(all_dates.shape)

(1434,)

In [34]:
# STEP 3 — Build Date Dimension

dim_dates = pd.DataFrame({
    "full_date": all_dates
})

dim_dates["day"] = dim_dates["full_date"].dt.day
dim_dates["month"] = dim_dates["full_date"].dt.month
dim_dates["month_name"] = dim_dates["full_date"].dt.month_name()
dim_dates["quarter"] = dim_dates["full_date"].dt.quarter
dim_dates["year"] = dim_dates["full_date"].dt.year
dim_dates["weekday"] = dim_dates["full_date"].dt.day_name()

dim_dates.head()

   full_date  day  month month_name  quarter  year   weekday
0 2014-01-03    3      1    January        1  2014    Friday
1 2014-01-04    4      1    January        1  2014  Saturday
2 2014-01-05    5      1    January        1  2014    Sunday
3 2014-01-06    6      1    January        1  2014    Monday
4 2014-01-07    7      1    January        1  2014   Tuesday

In [35]:
# STEP 4 — Weekend Flag
dim_dates["is_weekend"] = dim_dates["weekday"].isin(
    ["Saturday", "Sunday"]
)

In [36]:
# Add Surrogate Key
dim_dates.insert(
    0,
    "date_key",
    range(1, len(dim_dates) + 1)
)

dim_dates.head()

,date_key,full_date,day,month,month_name,quarter,year,weekday,is_weekend
0,1,2014-01-03,3,1,January,1,2014,Friday,False
1,2,2014-01-04,4,1,January,1,2014,Saturday,True
2,3,2014-01-05,5,1,January,1,2014,Sunday,True
3,4,2014-01-06,6,1,January,1,2014,Monday,False
4,5,2014-01-07,7,1,January,1,2014,Tuesday,False

#Load To PostgreSQL

In [37]:
dim_dates.to_sql(
    "dim_dates",
    engine,
    schema="retail",
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

print("dim_dates loaded successfully")

dim_dates loaded successfully

# Create Fact Sale fact_sales

In [38]:
# STEP 1 — Merge Customer Keys
fact_sales = df.merge(
    dim_customers,
    on=["customer_id", "customer_name", "segment"],
    how="left"
)

In [39]:
# STEP 2 — Merge Product Keys
fact_sales = fact_sales.merge(
    dim_products,
    on=[
        "product_id",
        "product_name",
        "category",
        "sub_category"
    ],
    how="left"
)

In [40]:
# STEP 3 — Merge Geography Keys
fact_sales = fact_sales.merge(
    dim_geography,
    on=[
        "country",
        "city",
        "state",
        "postal_code",
        "region"
    ],
    how="left"
)

In [42]:
# STEP 4 — Merge Shipping Keys
fact_sales = fact_sales.merge(
    dim_shipping,
    on=["ship_mode"],
    how="left"
)

In [43]:
# STEP 5 — Merge Order Date Keys
fact_sales = fact_sales.merge(
    dim_dates[["date_key", "full_date"]],
    left_on="order_date",
    right_on="full_date",
    how="left"
)

fact_sales.rename(
    columns={"date_key": "order_date_key"},
    inplace=True
)

fact_sales.drop(columns=["full_date"], inplace=True)

In [44]:
# STEP 6 — Merge Ship Date Keys
fact_sales = fact_sales.merge(
    dim_dates[["date_key", "full_date"]],
    left_on="ship_date",
    right_on="full_date",
    how="left"
)

fact_sales.rename(
    columns={"date_key": "ship_date_key"},
    inplace=True
)

fact_sales.drop(columns=["full_date"], inplace=True)

In [46]:
fact_sales.columns.tolist()

['row_id',
 'order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'segment',
 'country',
 'city',
 'state',
 'postal_code',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit',
 'customer_key',
 'product_key',
 'geography_key',
 'shipping_key_x',
 'shipping_key_y',
 'order_date_key',
 'ship_date_key']

In [47]:
fact_sales = fact_sales.drop(
    columns=["shipping_key_x"]
)

fact_sales = fact_sales.rename(
    columns={"shipping_key_y": "shipping_key"}
)

In [48]:
fact_sales.columns.tolist()

['row_id',
 'order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'segment',
 'country',
 'city',
 'state',
 'postal_code',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit',
 'customer_key',
 'product_key',
 'geography_key',
 'shipping_key',
 'order_date_key',
 'ship_date_key']

In [49]:
# STEP 7 — Create Final Fact Table
fact_sales_final = fact_sales[
    [
        "row_id",
        "order_id",
        "order_date_key",
        "ship_date_key",
        "customer_key",
        "product_key",
        "geography_key",
        "shipping_key",
        "sales",
        "quantity",
        "discount",
        "profit"
    ]
]

print(fact_sales_final.shape)

fact_sales_final.head()

(9994, 12)

,row_id,order_id,order_date_key,ship_date_key,customer_key,product_key,geography_key,shipping_key,sales,quantity,discount,profit
0,1,CA-2016-152156,1011,1014,1,1,1,1,261.96,2,0.00,41.91
1,2,CA-2016-152156,1011,1014,1,2,1,1,731.94,3,0.00,219.58
2,3,CA-2016-138688,863,867,2,3,2,1,14.62,2,0.00,6.87
3,4,US-2015-108966,623,630,3,4,3,2,957.58,5,0.45,-383.03
4,5,US-2015-108966,623,630,3,5,3,2,22.37,2,0.20,2.52

# Load Fact Table

In [50]:
fact_sales_final.to_sql(
    "fact_sales",
    engine,
    schema="retail",
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

print("fact_sales loaded successfully")

fact_sales loaded successfully